name: PS3 Build Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make git gcc g++ libgmp3-dev libmpfr-dev libmpc-dev zlib1g-dev libncurses-dev bison flex texinfo autoconf automake libtool pkg-config patch webp ffmpeg

    - name: Install PS3DEV SDK
      run: |
        git clone https://github.com/ps3dev/ps3dev.git
        cd ps3dev
        export PS3DEV=/usr/local/ps3dev
        export PATH=$PATH:$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin
        
    - name: Convert Audio to AT3
      run: |
        if [ -f "sound.mp3" ]; then
          ffmpeg -i sound.mp3 -acodec atrac3 -b:a 132k SND0.AT3 || echo "Ses donusturulemedi"
        fi

    - name: Compile and Package
      run: |
        export PS3DEV=/usr/local/ps3dev
        export PATH=$PATH:$PS3DEV/bin:$PS3DEV/ppu/bin:$PS3DEV/spu/bin

    - name: Upload Finished PS3 PKG
      uses: actions/upload-artifact@v4
  
      with:
        name: Kitty-Tetris-PS3-Package
        path: "*.pkg"
